// Script to generate static sitemap.xml after build
const fs = require('fs');
const path = require('path');

const baseUrl = 'https://ingredientsub.com';
const today = new Date().toISOString().split('T')[0];

// Get slugs from out folder (generated by Next.js build)
const outDir = path.join(__dirname, '..', 'out', 'substitute');
const slugs = fs.readdirSync(outDir).filter(f => 
  fs.statSync(path.join(outDir, f)).isDirectory()
);

let xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${baseUrl}/</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
`;

slugs.forEach(slug => {
  xml += `  <url>
    <loc>${baseUrl}/substitute/${slug}/</loc>
    <lastmod>${today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
`;
});

xml += `</urlset>`;

// Write to out folder (for deployment)
fs.writeFileSync(path.join(__dirname, '..', 'out', 'sitemap.xml'), xml);
console.log(`✅ sitemap.xml generated with ${slugs.length + 1} URLs`);

// Also copy robots.txt to out folder
const robots = `User-agent: *
Allow: /

Sitemap: ${baseUrl}/sitemap.xml
`;
fs.writeFileSync(path.join(__dirname, '..', 'out', 'robots.txt'), robots);
console.log('✅ robots.txt copied to out folder');
